### ISSUE TITLE
Didact with dark themes problem

### ISSUE THREAD

**Issue by weimeilin79** [openshift-integration/camel-k-example-basic#9]
In the didact instructions, some of the foreground text is white and background is white, making it hard to read![Screen Shot 2020-04-08 at 8 09 39 PM](https://user-images.githubusercontent.com/2534483/78844819-e6c63b00-79d4-11ea-93d5-b5eef3afb714.png)

**Comment by apupier** [comment]
This was fixed in VS Code Didact https://github.com/redhat-developer/vscode-didact/issues/92
